# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=128)),
                ('method', models.CharField(max_length=16)),
                ('request', models.BinaryField(default=b'')),
                ('response', models.BinaryField(default=b'')),
                ('db_updated', models.BooleanField(default=False)),
                ('create_at', models.IntegerField(default=time.time)),
                ('request_md5', models.CharField(default='', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=128)),
                ('method', models.CharField(max_length=16)),
                ('request', models.BinaryField(default=b'')),
                ('response', models.BinaryField(default=b'')),
                ('db_updated', models.BooleanField(default=False)),
                ('create_at', models.IntegerField(default=time.time)),
            ],
        ),
    ]
