# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acipenser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcache',
            name='request_md5',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='availablerequest',
            name='path',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='availablerequest',
            name='request_md5',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='requestcache',
            name='path',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
